//VARIAVEIS GLOBAIS PARA O SENSOR DE TEMPERATURA E HUMIDADE
var htu21d = {
    MAX_TEMP_CONVERSION: 55,// milliseconds
    MAX_HUMI_CONVERSION: 16,// ms
    MAX_RESET_DELAY: 15,// ms
    HTU21D_I2CADDR: 0x40,
    HTU21D_READTEMP_NH: 0xF3,
    HTU21D_READHUMI_NH: 0xF5,
    HTU21D_WRITEREG: 0xE6,
    HTU21D_READREG: 0xE7,
    HTU21D_RESET: 0xFE,
    HTDU21D_ADDRESS: 0x40,
    TRIGGER_TEMP_MEASURE_HOLD: 0xE3,
    TRIGGER_HUMD_MEASURE_HOLD: 0xE5,
    TRIGGER_TEMP_MEASURE_NOHOLD: 0xF3,
    TRIGGER_HUMD_MEASURE_NOHOLD: 0xF5,
    WRITE_USER_REG: 0xE6,
    READ_USER_REG: 0xE7,
    SOFT_RESET: 0xFE
};
module.exports = htu21d;